import React from 'react';
import GlassCard from '../components/ui/GlassCard';

export default function Disclaimer() {
    return (
        <div className="w-full min-h-screen pt-20 pb-32 px-6 flex flex-col items-center relative z-20">
            <div className="w-full max-w-4xl space-y-12 animate-fade-in-up">
                
                <div className="text-center space-y-6">
                    <h1 className="text-4xl md:text-5xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white to-white/60">
                        Medical Disclaimer
                    </h1>
                    <blockquote className="text-xl md:text-2xl text-text-muted font-medium italic border-l-4 border-accent pl-6 mx-auto max-w-3xl text-left">
                        "Esillio OS provides biological intelligence and data organization, but it is fundamentally an informational productivity tool—not a medical device or a substitute for professional healthcare."
                    </blockquote>
                </div>

                <GlassCard className="p-8 md:p-12 space-y-8 border-accent/20">
                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white">1. Not Medical Advice</h2>
                        <p className="text-text-muted leading-relaxed">
                            All insights, summaries, risk analyses, and timeline extractions generated by Esillio OS (and its connected AI agents) are provided for informational and educational purposes only. This software does not offer medical advice, diagnoses, or treatment recommendations. Always consult a qualified physician or healthcare provider regarding any medical condition or treatment.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white">2. AI Hallucination & Accuracy Risk</h2>
                        <p className="text-text-muted leading-relaxed">
                            Esillio OS leverages advanced Large Language Models (LLMs) to parse your health data. While these models are highly capable, they can hallucinate (generate false information), misinterpret context, or omit critical details from your medical records. You must verify any AI-generated insight against your original medical documents before acting upon it.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white">3. Limitation of Liability</h2>
                        <p className="text-text-muted leading-relaxed">
                            The developers of Esillio OS are not liable for any misinterpretation of data, missed diagnoses, health complications, or damages resulting from the use of this software. By using Esillio OS, you acknowledge that you are using a self-hosted intelligence tool entirely at your own risk.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white">4. Emergency Situations</h2>
                        <p className="text-text-muted leading-relaxed">
                            Never disregard professional medical advice or delay in seeking it because of something you have read or generated in Esillio OS. If you think you may have a medical emergency, call your doctor, go to the emergency department, or call emergency services immediately.
                        </p>
                    </section>
                </GlassCard>
            </div>
        </div>
    );
}
