import React from 'react';

const ClinicianSummary = ({ data }) => {
  if (!data || !data.summary) return null;
  
  const { summary, patient } = data;

  return (
    <div className="p-8 max-w-4xl mx-auto bg-white text-black min-h-screen" id="clinician-summary">
      <div className="border-b-2 border-black pb-4 mb-6 flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-bold uppercase tracking-widest">Esillio Clinical Summary</h1>
          <p className="text-gray-600 mt-1">Generated on: {new Date().toLocaleDateString()}</p>
        </div>
        <div className="text-right">
          <p className="font-semibold">Patient ID: {patient?.id || 'Unknown'}</p>
          <p className="text-gray-600">{patient?.email || 'N/A'}</p>
        </div>
      </div>

      <div className="mb-8">
        <h2 className="text-xl font-bold uppercase border-b border-gray-300 pb-2 mb-4">Active Conditions & Diagnoses</h2>
        {summary.active_conditions?.length > 0 ? (
          <ul className="list-disc pl-5 space-y-2">
            {summary.active_conditions.map((c, i) => (
              <li key={i}>
                <span className="font-semibold">{c.title}</span>
                {c.description && <p className="text-sm text-gray-700 mt-1">{c.description}</p>}
                <p className="text-xs text-gray-500 mt-1">Date: {c.timestamp ? new Date(c.timestamp).toLocaleDateString() : 'Unknown'}</p>
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-gray-600 italic">No active conditions recorded.</p>
        )}
      </div>

      <div className="mb-8">
        <h2 className="text-xl font-bold uppercase border-b border-gray-300 pb-2 mb-4">Current Medications</h2>
        {summary.current_medications?.length > 0 ? (
          <ul className="list-disc pl-5 space-y-2">
            {summary.current_medications.map((m, i) => (
              <li key={i}>
                <span className="font-semibold">{m.title}</span>
                {m.description && <p className="text-sm text-gray-700 mt-1">{m.description}</p>}
                <p className="text-xs text-gray-500 mt-1">Date: {m.timestamp ? new Date(m.timestamp).toLocaleDateString() : 'Unknown'}</p>
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-gray-600 italic">No current medications recorded.</p>
        )}
      </div>

      <div className="mb-8">
        <h2 className="text-xl font-bold uppercase border-b border-gray-300 pb-2 mb-4">Recent Biomarkers & Labs</h2>
        {summary.recent_biomarkers?.length > 0 ? (
          <ul className="list-disc pl-5 space-y-2">
            {summary.recent_biomarkers.map((b, i) => (
              <li key={i}>
                <span className="font-semibold">{b.title}</span>
                {b.description && <p className="text-sm text-gray-700 mt-1">{b.description}</p>}
                <p className="text-xs text-gray-500 mt-1">Date: {b.timestamp ? new Date(b.timestamp).toLocaleDateString() : 'Unknown'}</p>
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-gray-600 italic">No recent biomarkers recorded.</p>
        )}
      </div>
      
      <div className="mt-12 pt-4 border-t border-gray-300 text-center text-xs text-gray-500">
        <p>This report was generated by Esillio OS. It is a compiled summary of user-provided health records.</p>
        <p>For clinical use, please verify all information with the patient or original laboratory documents.</p>
      </div>
    </div>
  );
};

export default ClinicianSummary;
